### ISSUE TITLE
potential security vulnerabilities

### ISSUE THREAD

**Issue by AramSol** [twolfson/grunt-zip#54]
Hi all,
it seem there is a security issue with the jszip package that used in grunt-zip>0.14.0.
i got the the warning from GitHub after upgrading grunt-zip to lastest.
![image](https://user-images.githubusercontent.com/39582300/154303479-f73c7703-2d38-4a9c-8ab7-def8b3d4d0df.png)
there is the info that i get by using npm audit
![image](https://user-images.githubusercontent.com/39582300/154302805-de257aec-89b2-481b-b0a1-399c5224fbbb.png)
and the only package that use jszip can be seen here
![image](https://user-images.githubusercontent.com/39582300/154460121-c7a46b3a-3e26-47cb-bf72-480af1c4a527.png)

**Comment by twolfson** [comment]
GitHub is still processing the advisory so we haven't yet received a PR for it. The advisory doesn't unlikely to impact `grunt-zip` users since it's around prototype pollution: https://github.com/advisories/GHSA-jg8v-48h5-wgxg

If this is high priority to you, please submit a PR. Otherwise, we'll be waiting for the one from GitHub's dependabot

**Comment by AramSol** [comment]
@twolfson, thanks for fast response.
i just wondering if `grunt-zip` would still be working with `jszip` >3.7.0?

**Comment by twolfson** [comment]
I don't have the bandwidth to pick this up but you can prob check their changelog to see what happened between 2.5.0 and 3.7.0

**Comment by twolfson** [comment]
This has been resolved in `grunt-zip@0.20.0` by upgrading to `jszip@2.7.0`.
